#+TITLE: Wieland Hoffmann

This is the +end of the internet+ GitHub page of Wieland Hoffmann.
You can find me at various places around the web, including [[https://github.com/mineo/][GitHub]],
[[https://musicbrainz.org/user/Mineo][MusicBrainz]] and the [[https://unix.stackexchange.com/users/4699/wieland][Unix & Linux Stack Exchange]].

Other than that, there's not much to see here at the moment, except
for a short list of software I've written or contributed to.  For a
more complete list, check out [[https://www.openhub.net/accounts/mineo][my Open Hub profile]].

* Projects
** Applications
   :PROPERTIES:
   :CUSTOM_ID: applications
   :END:

- [[https://pypi.python.org/pypi/abzer][abzer]] is an application to submit data to the [[https://acousticbrainz.org/][AcousticBrainz]] database.
- [[https://github.com/mineo/dhis][dhis]] can be used to create a list of information (including cover
  art) for a users most listened to albums, as tracked by [[https://last.fm][last.fm]].
- [[https://github.com/mineo/hgidr][hgidr]] is an application that helps me keep track of TV shows I've
  seen by saving information about the last seen episode of each show.
- [[https://lala.readthedocs.org/en/latest/][lala]] is an IRC bot written in the Python programming language.
- [[https://pypi.python.org/pypi/mplayer-autocmd][mplayer-autocmd]] provides per-file options and keybindings for the [[http://mpv.io/][mpv]]
  media player.
- [[https://github.com/mineo/pypi2pkgbuild][pypi2pkgbuild]] is an application to semi-automatically create [[https://www.archlinux.org/pacman/PKGBUILD.5.html][PKGBUILD]]s for
  packages from [[https://pypi.python.org/pypi][PyPI]].
- [[https://sagbescheid.readthedocs.org/en/latest/][sagbescheid]] is a notification daemon for state changes in [[http://freedesktop.org/wiki/Software/systemd/][systemd]] units.

** Libraries
   :PROPERTIES:
   :CUSTOM_ID: libraries
   :END:
- [[https://pypi.python.org/pypi/enumerate_skip/][enumerate_skip]] is a library that extends Pythons [[https://docs.python.org/2/library/functions.html#enumerate][enumerate]]
  function with methods to adjust the count values returned while
  iterating over it.
- [[https://github.com/mineo/ilmwetter][ilmwetter]] is a [[http://scrapy.org/][Scrapy]] scraper for getting information about the weather in
  Ilmenau.
- [[https://github.com/mineo/mpd_pydb][mpd_pydb]] allows accessing an [[http://www.musicpd.org/][MPD]] database via Python.
- [[https://github.com/mineo/yatemplate][yatemplate]] is an Emacs library that uses [[https://capitaomorte.github.io/yasnippet/][YASnippet]] to provide file templates.

** MusicBrainz
   :PROPERTIES:
   :CUSTOM_ID: musicbrainz
   :END:

I'm a regular contributor to the MusicBrainz project, contributing
both data and code.

So far, most of the code that I wrote for the project has been in one
of the following projects:

- [[https://github.com/mineo/gocaa][gocaa]] is a library written in the [[http://golang.org/][Go]] programming language to
  access data in the [[https://coverartarchive.org/][Cover Art Archive]].
- [[https://github.com/mineo/mb2wikidatabot][mb2wikidatabot]] is an application to automatically enter [[https://musicbrainz.org][MusicBrainz]]
  identifiers into [[https://wikidata.org][Wikidata]].
- [[https://github.com/mineo/mb-places-map][mb-places-map]] is a map showing all places with coordinates in the [[https://musicbrainz.org][MusicBrainz]]
  database. You can view it +[[http://mbsandbox.org/~mineo/places/places.html][online]]+. Until I find a new place to host it, the map
  with old data can be found [[https://mineo.github.io/mb-places-map/src/places.html#4/50.68/10.92][here]].
- [[https://picard.musicbrainz.org/][MusicBrainz Picard]] is an application for tagging and renaming audio
  files.
  - I also maintain a few plugins in a separate [[https://github.com/mineo/mbstuff/tree/master/picard/plugins][repository]].
- [[https://python-musicbrainzngs.readthedocs.org/en/latest/][python-musicbrainzngs]] is a library for accessing MusicBrainz data in Python.

** Other
   :PROPERTIES:
   :CUSTOM_ID: other
   :END:

- [[https://github.com/mineo/shellcheck-travis][shellcheck-travis]] is a respository demonstrating the use of [[http://www.shellcheck.net/][shellcheck]] on
  [[https://travis-ci.org/][Travis CI]].

#+BEGIN_SRC emacs-lisp :results silent :exports none
(setq org-publish-project-alist nil)
(setq source-dir (file-name-directory (buffer-file-name)))
(add-to-list 'org-publish-project-alist
              `("github"
                :base-directory ,source-dir
                :publishing-directory ,source-dir
                :base-extension "org"
                :index-filename "index.org"
                :publishing-function (org-html-publish-to-html)
                :htmlized-source t
                :html-doctype "html5"
                :html-container "div"
                :html-head "<link href='//fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>"
                :html-link-use-abs-url nil
                :html-postamble auto
                :html-preamble t
                :html-scripts t
                :html-style t
                :html5-fancy nil
                :html-head-extra "<link rel='stylesheet' type='text/css' href='style.css' /> "
                :section-numbers nil
                :with-author nil
                :with-sub-superscript nil
                :with-toc nil
                :with-timestamps nil
                ))
(org-publish "github" t)
#+END_SRC
