#+TITLE: Quotes
#+OPTIONS: toc:t

* Warbreaker
  :PROPERTIES:
  :CUSTOM_ID: warbreaker
  :END:

#+BEGIN_QUOTE
“Mocking a woman is like drinking too much wine. It may be fun for a
short time, but the hangover is hell.”
#+HTML: <cite>
-- [[http://brandonsanderson.com/warbreaker-chapter-seven/][Chapter 7]]
#+HTML: </cite>
#+END_QUOTE

#+BEGIN_QUOTE
“You're a very difficult person to manipulate, you know.”\\
“Nonsense,” he said. "You just have to promise me that I won't have to
do a thing, and then I'll do anything you want."\\
“Anything?”\\
“Anything that doesn't require doing anything.”\\
“That's nothing, then.”\\
“Is it?”\\
“Yes.”\\
“Well, that's something.”\\
#+HTML: <cite>
-- [[http://brandonsanderson.com/warbreaker-chapter-sixteen/][Chapter 16]]
#+HTML: </cite>
#+END_QUOTE

* Wilde Reise durch die Nacht
  :PROPERTIES:
  :CUSTOM_ID: wrddn
  :END:

#+BEGIN_QUOTE
“Wir müssen in die Küstenregion, da treiben sich die meisten
Jungfrauen rum. Sie sind da, weil dort auch die meisten Drachen
verkehren.”\\
“Sollten sie sich dann nicht lieber im inneren Teil der Insel aufhalten?”\\
“Versteh einer die Weiber!” gab das Mischwesen zurück.
#+HTML: <cite>
-- Page 29
#+HTML: </cite>
#+END_QUOTE

* The Wheel of Time
  :PROPERTIES:
  :CUSTOM_ID: wheel_of_time
  :END:

** The Eye of the World
   :PROPERTIES:
   :CUSTOM_ID: eye_of_the_world
   :END:
#+BEGIN_QUOTE
With all his heart and desperation he silently shouted at Bela to run
like the wind, silently tried to will strength into her. /Run!/ His
skin prickled, and his bones felt as if they were freezing, ready to
split open. /The Light help her, run!/ And Bela ran.
#+HTML: <cite>
-- Page 149
#+HTML: </cite>
#+END_QUOTE

#+BEGIN_QUOTE
“Ila was giving me advice an being a woman.” Egwene replied
absently. He began laughing and she gave him a hooded, dangerous look
that he failed to see.\\
“Advice! Nobody tells us how to be men. We just are.”\\
“That,” Egwene said, “is probably why you make such a bad job of it.”
#+HTML: <cite>
-- Page 413
#+HTML: </cite>
#+END_QUOTE

#+BEGIN_QUOTE
Perrin looked at Egwene again and blinked away hot tears. He touched
his axe and wondered if he had the courage. In the last minutes, when
the ravens descended on them, when all hope was gone, would he have
the courage to spare her the death the fox had dies? /Light make me
strong!/
#+HTML: <cite>
-- Page 432
#+HTML: </cite>
#+END_QUOTE

#+BEGIN_QUOTE
“You’ll use it.”\\
Perrin raised the axe to throw it in the pool, but Elyas caught his
wrist.\\
“You’ll use it, boy, and as long as you hate using it, you will use it
more wisely than most men would. Wait. If ever you don’t hate it any
longer, then will be the time to throw it as far as you can and run
the other way.”
#+HTML: <cite>
-- Page 440
#+HTML: </cite>
#+END_QUOTE
